version: 2.1
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }} 
      - run:
          name: run test
          command: ./gradlew test
      - run:
          name: download go
          command: wget -O - "https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz" | tar -zxvf - -C ./ 
      - run:
          name: get ecr-helper
          command: ./go/bin/go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
      - run:
          name: set go path
          command: echo 'export PATH=$HOME/go/bin:$PATH' >> $BASH_ENV 
      - run:
          name: push ecr
          command: ./gradlew jib
workflows:
  test_and_push_image:
    jobs:
      - build
        
