version: 2.1
jobs:
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: run test
          command: ./gradlew test
  push_image:
    working_directory: ~/workspace
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: download go
          command: wget -O - "https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz" | tar -C /usr/local -xzf -
      - run:
          name: get ecr-helper
          command: ./go/bin/go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
      - run:
          name: push ecr
          command: export PATH=$PATH:/usr/local/go/bin; ./gradlew jib
workflows:
  test_and_push_image:
    jobs:
      - test
      - push_image:
          requires:
            - test
        
